/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EpochTime = bigint;
export interface ParkingSession {
  'exitTime' : [] | [EpochTime],
  'vehicleType' : VehicleType,
  'entryTime' : EpochTime,
  'vehicleNumber' : string,
  'totalCost' : [] | [bigint],
  'slotId' : SlotId,
  'customerId' : UserId,
}
export type ParkingSessionId = string;
export interface ParkingSlot {
  'id' : SlotId,
  'vehicleType' : [] | [VehicleType],
  'name' : string,
  'isOccupied' : boolean,
}
export type SlotId = number;
export type UserId = Principal;
export interface UserProfile {
  'vehicleType' : VehicleType,
  'username' : string,
  'vehicleNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'twoWheeler' : null } |
  { 'fourWheeler' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateParkingSlot' : ActorMethod<[string, [] | [VehicleType]], SlotId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'finalizeParkingSession' : ActorMethod<[ParkingSessionId], ParkingSession>,
  'getAllParkingSessions' : ActorMethod<[], Array<ParkingSession>>,
  'getAvailableSlots' : ActorMethod<[], Array<ParkingSlot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerSessions' : ActorMethod<[], Array<ParkingSession>>,
  'getIncomeStats' : ActorMethod<
    [],
    { 'dailyIncome' : bigint, 'monthlyIncome' : bigint }
  >,
  'getLatestVehicleNumber' : ActorMethod<[], [] | [string]>,
  'getParkingSession' : ActorMethod<[ParkingSessionId], [] | [ParkingSession]>,
  'getPricing' : ActorMethod<[], [bigint, bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerParkingSession' : ActorMethod<
    [SlotId, string, VehicleType],
    ParkingSessionId
  >,
  'removeParkingSlot' : ActorMethod<[SlotId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPricing' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];