/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'twoWheeler' : IDL.Null,
  'fourWheeler' : IDL.Null,
});
export const SlotId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ParkingSessionId = IDL.Text;
export const EpochTime = IDL.Int;
export const UserId = IDL.Principal;
export const ParkingSession = IDL.Record({
  'exitTime' : IDL.Opt(EpochTime),
  'vehicleType' : VehicleType,
  'entryTime' : EpochTime,
  'vehicleNumber' : IDL.Text,
  'totalCost' : IDL.Opt(IDL.Nat),
  'slotId' : SlotId,
  'customerId' : UserId,
});
export const ParkingSlot = IDL.Record({
  'id' : SlotId,
  'vehicleType' : IDL.Opt(VehicleType),
  'name' : IDL.Text,
  'isOccupied' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'vehicleType' : VehicleType,
  'username' : IDL.Text,
  'vehicleNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateParkingSlot' : IDL.Func(
      [IDL.Text, IDL.Opt(VehicleType)],
      [SlotId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'finalizeParkingSession' : IDL.Func([ParkingSessionId], [ParkingSession], []),
  'getAllParkingSessions' : IDL.Func([], [IDL.Vec(ParkingSession)], ['query']),
  'getAvailableSlots' : IDL.Func([], [IDL.Vec(ParkingSlot)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerSessions' : IDL.Func([], [IDL.Vec(ParkingSession)], ['query']),
  'getIncomeStats' : IDL.Func(
      [],
      [IDL.Record({ 'dailyIncome' : IDL.Nat, 'monthlyIncome' : IDL.Nat })],
      ['query'],
    ),
  'getLatestVehicleNumber' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getParkingSession' : IDL.Func(
      [ParkingSessionId],
      [IDL.Opt(ParkingSession)],
      ['query'],
    ),
  'getPricing' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerParkingSession' : IDL.Func(
      [SlotId, IDL.Text, VehicleType],
      [ParkingSessionId],
      [],
    ),
  'removeParkingSlot' : IDL.Func([SlotId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPricing' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'twoWheeler' : IDL.Null,
    'fourWheeler' : IDL.Null,
  });
  const SlotId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ParkingSessionId = IDL.Text;
  const EpochTime = IDL.Int;
  const UserId = IDL.Principal;
  const ParkingSession = IDL.Record({
    'exitTime' : IDL.Opt(EpochTime),
    'vehicleType' : VehicleType,
    'entryTime' : EpochTime,
    'vehicleNumber' : IDL.Text,
    'totalCost' : IDL.Opt(IDL.Nat),
    'slotId' : SlotId,
    'customerId' : UserId,
  });
  const ParkingSlot = IDL.Record({
    'id' : SlotId,
    'vehicleType' : IDL.Opt(VehicleType),
    'name' : IDL.Text,
    'isOccupied' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'vehicleType' : VehicleType,
    'username' : IDL.Text,
    'vehicleNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateParkingSlot' : IDL.Func(
        [IDL.Text, IDL.Opt(VehicleType)],
        [SlotId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'finalizeParkingSession' : IDL.Func(
        [ParkingSessionId],
        [ParkingSession],
        [],
      ),
    'getAllParkingSessions' : IDL.Func(
        [],
        [IDL.Vec(ParkingSession)],
        ['query'],
      ),
    'getAvailableSlots' : IDL.Func([], [IDL.Vec(ParkingSlot)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerSessions' : IDL.Func([], [IDL.Vec(ParkingSession)], ['query']),
    'getIncomeStats' : IDL.Func(
        [],
        [IDL.Record({ 'dailyIncome' : IDL.Nat, 'monthlyIncome' : IDL.Nat })],
        ['query'],
      ),
    'getLatestVehicleNumber' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getParkingSession' : IDL.Func(
        [ParkingSessionId],
        [IDL.Opt(ParkingSession)],
        ['query'],
      ),
    'getPricing' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerParkingSession' : IDL.Func(
        [SlotId, IDL.Text, VehicleType],
        [ParkingSessionId],
        [],
      ),
    'removeParkingSlot' : IDL.Func([SlotId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPricing' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };