/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface ParkingSlot {
    id: SlotId;
    vehicleType?: VehicleType;
    name: string;
    isOccupied: boolean;
}
export type SlotId = number;
export interface ParkingSession {
    exitTime?: EpochTime;
    vehicleType: VehicleType;
    entryTime: EpochTime;
    vehicleNumber: string;
    totalCost?: bigint;
    slotId: SlotId;
    customerId: UserId;
}
export type ParkingSessionId = string;
export interface UserProfile {
    vehicleType: VehicleType;
    username: string;
    vehicleNumber: string;
}
export type EpochTime = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleType {
    twoWheeler = "twoWheeler",
    fourWheeler = "fourWheeler"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateParkingSlot(slotName: string, vehicleType: VehicleType | null): Promise<SlotId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    finalizeParkingSession(sessionId: ParkingSessionId): Promise<ParkingSession>;
    getAllParkingSessions(): Promise<Array<ParkingSession>>;
    getAvailableSlots(): Promise<Array<ParkingSlot>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerSessions(): Promise<Array<ParkingSession>>;
    getIncomeStats(): Promise<{
        dailyIncome: bigint;
        monthlyIncome: bigint;
    }>;
    getLatestVehicleNumber(): Promise<string | null>;
    getParkingSession(sessionId: ParkingSessionId): Promise<ParkingSession | null>;
    getPricing(): Promise<[bigint, bigint]>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerParkingSession(slotId: SlotId, vehicleNumber: string, vehicleType: VehicleType): Promise<ParkingSessionId>;
    removeParkingSlot(slotId: SlotId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPricing(twoWheelerRate: bigint, fourWheelerRate: bigint): Promise<void>;
}
import type { EpochTime as _EpochTime, ParkingSession as _ParkingSession, ParkingSlot as _ParkingSlot, SlotId as _SlotId, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateParkingSlot(arg0: string, arg1: VehicleType | null): Promise<SlotId> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateParkingSlot(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateParkingSlot(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async finalizeParkingSession(arg0: ParkingSessionId): Promise<ParkingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeParkingSession(arg0);
                return from_candid_ParkingSession_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeParkingSession(arg0);
            return from_candid_ParkingSession_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParkingSessions(): Promise<Array<ParkingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParkingSessions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParkingSessions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSlots(): Promise<Array<ParkingSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerSessions(): Promise<Array<ParkingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerSessions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerSessions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomeStats(): Promise<{
        dailyIncome: bigint;
        monthlyIncome: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeStats();
            return result;
        }
    }
    async getLatestVehicleNumber(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestVehicleNumber();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestVehicleNumber();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParkingSession(arg0: ParkingSessionId): Promise<ParkingSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParkingSession(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParkingSession(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPricing(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricing();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricing();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerParkingSession(arg0: SlotId, arg1: string, arg2: VehicleType): Promise<ParkingSessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerParkingSession(arg0, arg1, to_candid_VehicleType_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerParkingSession(arg0, arg1, to_candid_VehicleType_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async removeParkingSlot(arg0: SlotId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeParkingSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeParkingSlot(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPricing(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPricing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPricing(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ParkingSession_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParkingSession): ParkingSession {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ParkingSlot_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParkingSlot): ParkingSlot {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehicleType]): VehicleType | null {
    return value.length === 0 ? null : from_candid_VehicleType_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ParkingSession]): ParkingSession | null {
    return value.length === 0 ? null : from_candid_ParkingSession_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EpochTime]): EpochTime | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SlotId;
    vehicleType: [] | [_VehicleType];
    name: string;
    isOccupied: boolean;
}): {
    id: SlotId;
    vehicleType?: VehicleType;
    name: string;
    isOccupied: boolean;
} {
    return {
        id: value.id,
        vehicleType: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.vehicleType)),
        name: value.name,
        isOccupied: value.isOccupied
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicleType: _VehicleType;
    username: string;
    vehicleNumber: string;
}): {
    vehicleType: VehicleType;
    username: string;
    vehicleNumber: string;
} {
    return {
        vehicleType: from_candid_VehicleType_n9(_uploadFile, _downloadFile, value.vehicleType),
        username: value.username,
        vehicleNumber: value.vehicleNumber
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exitTime: [] | [_EpochTime];
    vehicleType: _VehicleType;
    entryTime: _EpochTime;
    vehicleNumber: string;
    totalCost: [] | [bigint];
    slotId: _SlotId;
    customerId: _UserId;
}): {
    exitTime?: EpochTime;
    vehicleType: VehicleType;
    entryTime: EpochTime;
    vehicleNumber: string;
    totalCost?: bigint;
    slotId: SlotId;
    customerId: UserId;
} {
    return {
        exitTime: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.exitTime)),
        vehicleType: from_candid_VehicleType_n9(_uploadFile, _downloadFile, value.vehicleType),
        entryTime: value.entryTime,
        vehicleNumber: value.vehicleNumber,
        totalCost: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.totalCost)),
        slotId: value.slotId,
        customerId: value.customerId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twoWheeler: null;
} | {
    fourWheeler: null;
}): VehicleType {
    return "twoWheeler" in value ? VehicleType.twoWheeler : "fourWheeler" in value ? VehicleType.fourWheeler : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ParkingSession>): Array<ParkingSession> {
    return value.map((x)=>from_candid_ParkingSession_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ParkingSlot>): Array<ParkingSlot> {
    return value.map((x)=>from_candid_ParkingSlot_n14(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType | null): [] | [_VehicleType] {
    return value === null ? candid_none() : candid_some(to_candid_VehicleType_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicleType: VehicleType;
    username: string;
    vehicleNumber: string;
}): {
    vehicleType: _VehicleType;
    username: string;
    vehicleNumber: string;
} {
    return {
        vehicleType: to_candid_VehicleType_n2(_uploadFile, _downloadFile, value.vehicleType),
        username: value.username,
        vehicleNumber: value.vehicleNumber
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    twoWheeler: null;
} | {
    fourWheeler: null;
} {
    return value == VehicleType.twoWheeler ? {
        twoWheeler: null
    } : value == VehicleType.fourWheeler ? {
        fourWheeler: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
